In [4]:
def myfunction(a,b):
  try:
    answer = a/b
    return answer
  except ZeroDivisionError:
    return "Error: division by zero is not allowed."


#Call the function as follows:
result = myfunction(2,0)
print(result)

Error: division by zero is not allowed.


In [6]:
def myfunction2(c):
   try:
     answer = a/c
     return answer
   except NameError:
     return "Error: a is not define."

# Call the function as follows:
myfunction2(3)

'Error: a is not define.'

In [8]:
def myfunction3(b):
    mylist = [2, 3, 5, -7, 8, 0]
    idx = 0
    while idx<=6:
      try:
        print('Iteration:', idx, mylist[idx]/b)
      except IndexError:
        print(f'IndexError: index {idx} is out of range')

      idx = idx+1
      print('Iteration completed')

# Call the function as follows:
myfunction3(b=5)

Iteration: 0 0.4
Iteration completed
Iteration: 1 0.6
Iteration completed
Iteration: 2 1.0
Iteration completed
Iteration: 3 -1.4
Iteration completed
Iteration: 4 1.6
Iteration completed
Iteration: 5 0.0
Iteration completed
IndexError: index 6 is out of range
Iteration completed


In [10]:
def divide(a, b):
   try:
        a = float(a)
        b = float(b)

        if b == 0:
            print("Error: division by zero is not allowed.")
            return None

        result = a / b
        print('The result of division is', result)
        return result


   except ValueError:
        print("Error: inputs must be numeric values.")
        return None

# Call the function as follows:
divide("10",2)
divide(10,0)
divide(10, "two")

The result of division is 5.0
Error: division by zero is not allowed.
Error: inputs must be numeric values.


In [13]:
def read_file(filename):
    try:
      with open(filename, 'r') as file1:
          word_string = file1.read()
      print("File reading completed successfully")
      # FIX THE ERROR BELOW
      # FileNotFoundError
      return word_string

    except FileNotFoundError:
        print(f"Error: file '{filename}' not found.")
        return None
# Call the function as follows:
read_file("Q1.txt")


Error: file 'Q1.txt' not found.


In [7]:
def check_rows(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every row."""
    for i, row in enumerate(grid):
        if set(row) != expected_numbers:
            return False, f"Row {i + 1}: {row}"
    return True, None


def check_cols(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every column."""
    sudoku_size = len(grid)   # FIX: local scope, no global
    for j in range(sudoku_size):
        column = [grid[i][j] for i in range(sudoku_size)]
        if set(column) != expected_numbers:
            return False, f"Column {j + 1}: {column}"
    return True, None


def check_blocks(grid, expected_numbers):
    """Checks for uniqueness and completeness (1-9) in every 3x3 block."""
    for block_row_start in range(0, 9, 3):
        for block_col_start in range(0, 9, 3):
            block = []
            for i in range(block_row_start, block_row_start + 3):
                for j in range(block_col_start, block_col_start + 3):
                    block.append(grid[i][j])

            if set(block) != expected_numbers:
                return False, f"Block at ({block_row_start + 1}, {block_col_start + 1})"
    return True, None


def is_sudoku_solved(grid):
    """
    Checks if the given 9x9 grid is a correctly solved Sudoku puzzle.
    """
    # Basic size check
    if len(grid) != 9 or any(len(row) != 9 for row in grid):
        print("Error: Grid must be exactly 9x9.")
        return False

    expected_numbers = set(range(1, 10))

    # Check rows
    is_valid, error_info = check_rows(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # Check columns
    is_valid, error_info = check_cols(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    # Check blocks
    is_valid, error_info = check_blocks(grid, expected_numbers)
    if not is_valid:
        print(f"Mistake found in {error_info}")
        return False

    return True



# calling the function as follows:

import numpy as np
grid = np.random.randint(1,10,(9,9))
print(grid)
is_sudoku_solved(grid.tolist())

solved_grid = [
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
]
is_sudoku_solved(solved_grid)



[[6 5 9 2 5 8 8 1 7]
 [5 1 6 3 3 9 8 4 6]
 [1 1 2 1 9 9 1 2 8]
 [5 7 1 7 9 4 3 5 7]
 [6 3 5 5 3 2 4 2 7]
 [9 1 5 4 6 5 1 6 1]
 [8 3 2 8 1 8 4 6 3]
 [8 7 9 9 1 2 1 1 4]
 [3 7 8 6 1 4 3 9 8]]
Mistake found in Row 1: [6, 5, 9, 2, 5, 8, 8, 1, 7]


True